### ISSUE TITLE
Don't use a hardcoded path to the json file

### ISSUE THREAD

**Issue by PissedCapslock** [TijlB99/tsd#2]
I can now do run
````
npm run build
````
to build the documentation, but that requires me to put the json file under `contents/docu.json` first.

The end goal of this project is to let this project publish an npm package that can be used in other projects.
A first step towards this is allowing to specify the input file.

Other things that we probably want to pass to the command to generate the documentation:

- The output path
- Path to the folder containing the images
- Path to the folder containing the snippets
- Path to the CSS/styling related files (if people want to use custom styling)

**Comment by TijlB99** [comment]
Solved using bash script.
See README for syntax.
