### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by PissedCapslock** [TijlB99/tsd#3]
The readme is now generated by gatsby.

It should:

- Give a brief explanation about what this project is
- Basic instructions on how to use it
- Full documentation on what is supported, e.g.
-- Supports typical HTML tags: `<p>`, `<i>`, ...
-- The supported special tags you can use like `{@link ...}`
-- How to include snippets (both inline as from external files)
-- How to include images
-- ...

**Comment by TijlB99** [comment]
Readme is improved.
